name: Build and publish PHP binaries

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MUSL_CROSS_MAKE_VERSION: 43fcb1e63786b96add78f89d7454709ae0159fa0
  PM_VERSION_MAJOR: "5"
  PHP_VERSION_BASE: "8.2"

jobs:
  android:
    name: Android arm64
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Install tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git re2c

      - name: Prepare compile.sh download cache
        id: download-cache
        uses: actions/cache@v4
        with:
          path: ./download_cache
          key: compile-sh-cache-ssl-https-${{ hashFiles('./compile.sh') }}
          restore-keys: compile-sh-cache-ssl-https-

      - name: Fetch compiler cache
        id: compiler-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/compiler
          key: musl-cross-make-${{ env.MUSL_CROSS_MAKE_VERSION }}

      - name: Checkout musl-cross-make
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: pmmp/musl-cross-make
          path: musl-cross-make
          ref: ${{ env.MUSL_CROSS_MAKE_VERSION }}

      - name: Build compiler
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        working-directory: musl-cross-make
        run: |
          echo "TARGET = aarch64-linux-musl" > config.mak
          make -j$(nproc)
          make install
          mv ./output "${{ github.workspace }}/compiler"

      - name: Compile PHP
        run: |
          export PATH="${{ github.workspace }}/compiler/bin:$PATH"

          # Used "set -ex" instead of hashbang since script isn't executed with hashbang
          set -ex
          trap "exit 1" ERR
          ./compile.sh -t android-aarch64 -x -j 4 -g -P ${{ env.PM_VERSION_MAJOR }} -c ./download_cache -D -z ${{ env.PHP_VERSION_BASE }}

      - name: Create tarball
        run: |
          tar -czf ./PHP-${{ env.PHP_VERSION_BASE }}-Android-arm64-PM${{ env.PM_VERSION_MAJOR }}.tar.gz bin
          tar -czf ./Z-PHP-${{ env.PHP_VERSION_BASE }}-Android-arm64-PM${{ env.PM_VERSION_MAJOR }}-debugging-symbols.tar.gz bin-debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: PHP-${{ env.PHP_VERSION_BASE }}-Android-PM${{ env.PM_VERSION_MAJOR }}
          path: |
            ./*PHP-${{ env.PHP_VERSION_BASE }}-Android-arm64-PM${{ env.PM_VERSION_MAJOR }}*.tar.gz
            install.log
            compile.sh
          if-no-files-found: error

      - name: Prepare workspace for upload
        if: failure()
        run: tar -czf workspace.tar.gz install_data

      - name: Upload workspace
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: PHP-${{ env.PHP_VERSION_BASE }}-Android-workspace-PM${{ env.PM_VERSION_MAJOR }}
          path: |
            workspace.tar.gz
          if-no-files-found: error
